// Generated by `go generate` at {{.Time}}

package main

import (
	"html/template"
)

var templates = map[string]*template.Template{
	{{- range $k, $v := .Templates}}
	"{{$k}}": template.Must(template.New("{{$k}}").Parse(`{{$v}}`)),
	{{- end}}
}
