if [ "$TERM_PROGRAM" == "Apple_Terminal" ]; then
	alias ls="ls -hG"
	PS1="\t \[\033[34m\]\W\[\033[0m\] "
else
	alias ls="ls -h --color"
	PS1="\t \[\033[1;34m\]\W\[\033[0m\] "
fi

alias la="ls -a"
alias ll="ls -l"
alias l="ls -la"

alias pstree="pstree -g 2"

export NODE_PATH="/usr/local/lib/node"
export EDITOR=vim
export DISPLAY=:0 # Useful for Linux

shopt -s globstar >/dev/null 2>&1  # Bash 4+ only
